### ISSUE TITLE
Bug: Redundant empty space on post headers

### ISSUE THREAD

**Issue by Wilker-a** [Docile-Alligator/Infinity-For-Reddit#30] opened 2019-10-27 18:39 UTC
posts in the fontpages often appears to have a long empty space after the options bar specially text posts and posts with external links...
![[a cropped screenshot of the app, showing the empty space]](https://user-images.githubusercontent.com/10854855/67639520-49b49180-f8cf-11e9-96cf-1a46f06dc58d.png)

if it helps with anything, the resolution is 480x740px, 72dpi

**Comment by Docile-Alligator** [comment] 2019-10-28 16:16
Thank you for your feedback. I only encounter this issue in an emulator. I thought it was a bug related to the emulator itself. What version of Android do you use? Is it 5.1?

**Comment by Wilker-a** [comment] 2019-10-28 21:25
yes, it is \^\^

**Comment by Docile-Alligator** [comment] 2019-10-29 07:04
Hi! The problem is fixed now (maybe). Wait for the next update.

**Comment by Docile-Alligator** [comment] 2019-11-01 03:02
Does the bug happen again after the update?

**Comment by Wilker-a** [comment] 2019-11-02 20:30
the issue is apparently gone now \^u\^

**Comment by Docile-Alligator** [comment] 2019-11-05 03:12
You are very welcome!

**Closed by Docile-Alligator** 2019-11-05 03:12 UTC

**Comment by sommv** [comment] 2019-12-28 16:26
Hi! I'm also on Android 5.1, downloaded the app from the play store today and experience this exact problem. I guess it's maybe not solved after all? Or is the update not on the play store yet?

**Comment by Wilker-a** [comment] 2020-01-06 00:11
i can confirm that the issue is back \^\^'

version 2.1.0 from the IzzyOnDroid F-Droid repository

**Comment by Docile-Alligator** [comment] 2020-02-12 07:25
Yes. I know why this happens, but my new solution doesn't seem to work.
