### ISSUE TITLE
Feature Request: Publish your app on F-Droid

### ISSUE THREAD

**Issue by baumell** [Docile-Alligator/Infinity-For-Reddit#21] opened 2019-09-18 08:14 UTC
Hello Docile-Alligator!

Thanks for your well designed Reddit-app.

I would love to see this app on f-droid. Have you thought about publishing it there?

[Here](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) is a quick start guide for publishing it there.

**Comment by Docile-Alligator** [comment] 2019-09-19 14:10
Hey, I thought about it but I don't know how to hide my API key and other secret info. I will publish to f-droid after I figuring it out.

**Comment by Poussinou** [comment] 2019-09-21 20:05
Hi, F-Droid contributor here,

F-Droid doesn't sign itself for API keys. If these keys are needed for the app to work, you'll have to put them directly in the source code (and yes, everybody will see them, but we have many apps on F-Droid that do that, and no problem until now so it should be ok), because we need the full source code to build the app. Maybe you could have a look at how [Slide](https://f-droid.org/packages/me.ccrama.redditslide/) ([source code](https://github.com/ccrama/Slide)) handle this problem.

I see no proprietary dependencies in the gradle so it's a good point :)

Still, you can open a [RFP](https://gitlab.com/fdroid/rfp/issues) on our side, and maybe get some help.

(duplicate of #2)

**Comment by Docile-Alligator** [comment] 2019-09-23 15:56
Hey thank you!

**Comment by IzzySoft** [comment] 2019-10-03 18:50
Chiming in: F-Droid Maintainer here. Main thing missing at the moment is an OSI-approved license (e.g. MIT, Apache 2.0, GPL …). Do you already have one in mind? Until everything is ready for inclusion with the official repo, I've taken your app into mine (it should show up with the next sync tomorrow [at this URL](https://apt.izzysoft.de/fdroid/index/apk/ml.docilealligator.infinityforreddit) – and being available via the F-Droid client for those having my repo configured). My library checker approves :smile:

**Comment by Docile-Alligator** [comment] 2019-10-03 22:50
Hi! Thank you! But in my repo there is no Reddit API key, so it should not be usable. Could you please give me some advice on how to properly include the API key in the repo? Because I don't think it is a good idea to plainly show the key in my repo.

**Comment by IzzySoft** [comment] 2019-10-03 23:23
If you mean me: that's outside of my experience (I'm no Android developer). As for "should not be usable": Are you saying the APK attached to `releases/` isn't there to be used? I'm just confused now. Or maybe I confused you: other than with the official F-Droid repo, I do not compile myself but pick the APKs provided by the developers. Looks like we didn't start on the same leg, and all is fine :smile:

**Comment by Docile-Alligator** [comment] 2019-10-03 23:32
All the apks in releases can be used since they contain the API key. I thought you wanted to compile the repo yourself. Haha.

**Comment by IzzySoft** [comment] 2019-10-04 06:11
Yes, ideally I'd do that (for F-Droid, that's the only way). But I'm no Android dev, have no build environment nor build experience… My area at F-Droid is mainly the maintenance of metadata (app descriptions, links etc).

**Comment by PopeRigby** [comment] 2019-11-04 18:19
Since you have a FOSS license now, are you able to start working on this again?

**Comment by Docile-Alligator** [comment] 2019-11-28 01:37
I will

**Comment by Docile-Alligator** [comment] 2020-02-12 07:18
https://www.reddit.com/r/Infinity_For_Reddit/comments/f23o0y/for_anyone_who_wants_to_use_fdroid/

Actually IzzySoft's repo is pretty good. You can see this post and add the repo to F-Droid to download Infinity. If I include this app in F-Droid's repo, then the API key has to be uploaded, and this is not good. Also, the apk signature will be changed to F-Droid's instead of mine.

**Closed by Docile-Alligator** 2020-02-12 07:18 UTC

**Comment by IzzySoft** [comment] 2020-02-12 07:29
Thanks! You app is of course welcome to stay with my repo :smiley:

**Comment by Docile-Alligator** [comment] 2020-02-12 08:02
Thank you very much!

**Comment by PopeRigby** [comment] 2020-02-12 15:10
How do other developers use API keys? I think it would be a better idea to put it in the official F-Droid repo, to make it more accessible.

**Comment by Docile-Alligator** [comment] 2020-02-23 02:28
Putting this in the official repo not only directly expose my API key but also change my app's release key to F-Droid's. This means the app installed on F-Droid will not be compatible with the one on Google Play. And this is not good so it's better to add this app to IzzySoft's repo.
