### ISSUE TITLE
Last image in multi-image posts doesn't always load

### ISSUE THREAD

**Issue by ReimuHKJ** [Docile-Alligator/Infinity-For-Reddit#548] opened 2021-11-25 23:02 UTC
It either only loads if another tab is opened and the you go back, or it just takes a long time before you can see it.

**Comment by scria1000** [comment] 2021-11-26 08:12
Hi, I can't reproduce this issue, going to need some more information.

What App version?
What Android version?
Does it happen with every post that has a gallery?
Or does it only happen with the gallery of (a) specific post(s)? If so, can you share a link to that post/those posts?

**Comment by ReimuHKJ** [comment] 2021-11-26 08:15
Version 5.1.1, Android 11.
I'm not sure when it happens, it seems to be the case about 90% of the
time. It either takes a long time or just doesn't load until another page
is loaded, and you can see it once you go back from that page.

**Comment by scria1000** [comment] 2021-11-26 12:20
Hi, I was able to reproduce this issue. [Excuse the post](https://www.reddit.com/r/ItalianFap/comments/qywbjr/supercontest_da_domani_le_8_vincitrici_dei/)

I made a pull request for this #549. Can you install the unsigned debug build below and tell us whether the issue persists?

https://github.com/Docile-Alligator/Infinity-For-Reddit/suites/4473852282/artifacts/119046449

**Comment by ReimuHKJ** [comment] 2021-11-26 14:23
Seems to be good now! Nice job!

**Comment by scria1000** [comment] 2021-12-01 18:38
can we close this?

**Closed** 2022-01-22 02:20 UTC
