### ISSUE TITLE
[Feature] Display Comment Gifs Automatically

### ISSUE THREAD

**Issue by 0rdinant** [Docile-Alligator/Infinity-For-Reddit#347] opened 2021-05-17 21:06 UTC
Currently gifs in comments [such as these](https://www.reddit.com/r/sbubby/comments/myz4f9/based_on_the_hit_video_game/gvyyqql/) appear as links instead of appearing in the comments themselves. Would there be a way to do this without using excessive resources?

**Comment by Docile-Alligator** [comment] 2021-05-28 15:50
Currently I don't know how to implement this. But I will try.

**Comment by Wladefant** [comment] 2022-08-18 20:42
Duplicate of #935

**Closed by Wladefant** 2022-08-18 20:42 UTC
