### ISSUE TITLE
[Feature request] Mark posts as read without an account.

### ISSUE THREAD

**Issue by Gwaenchanayo** [Docile-Alligator/Infinity-For-Reddit#770] opened 2022-05-12 23:38 UTC
Slide for Reddit has an option which allow posts to be marked as read when scrolled past even without an account. This makes it a lot easier to browse reddit as read post titles are in a different colour. Without it I end up re-reading the same post titles each time I open the client.

**Comment by Wladefant** [comment] 2022-08-15 17:28
Duplicate of #983

**Closed by Wladefant** 2022-08-15 17:28 UTC
Labels: type: enhancement
