### ISSUE TITLE
[Request] Indication that a post has been read

### ISSUE THREAD

**Issue by dchoi87** [Docile-Alligator/Infinity-For-Reddit#187] opened 2020-09-06 21:55 UTC
Could we get some indication that a post has been read? For example, in the official reddit app, the title is greyed on visit.

**Comment by OHermesJunior** [comment] 2020-09-07 15:07
Duplicate of #9 and #89

**Comment by Docile-Alligator** [comment] 2020-12-19 04:23
This will be available in v4.2.0.

**Closed by Docile-Alligator** 2020-12-19 04:23 UTC
