### ISSUE TITLE
Stuck notification after update to 5.0.0-beta2

### ISSUE THREAD

**Issue by cdysthe** [Docile-Alligator/Infinity-For-Reddit#429] opened 2021-08-05 22:46 UTC
After update to 5.0.0-beta2 I have a notification from Infinity I do not know what is and which can't be removed. If I kill Infinity the notification is back as soon as I run Infinity again. See screenshot 

https://imgur.com/a/xfGN0Ur

**Comment by KaKi87** [comment] 2021-08-06 19:36
Duplicate of #420

**Comment by bczsalba** [comment] 2021-08-08 14:21
> Duplicate of #420

It's not.

**Comment by Docile-Alligator** [comment] 2021-09-02 14:51
Fixed.

**Closed by Docile-Alligator** 2021-09-02 14:51 UTC
