### ISSUE TITLE
Feature request: being able to do a search in a multireddit

### ISSUE THREAD

**Issue by tiritibambix** [Docile-Alligator/Infinity-For-Reddit#530] opened 2021-11-13 22:34 UTC
Basically what the title says.

This app is just the best I've ever tried along with sync for Reddit. Awesome job ! The only thing I miss is the ability to search a post / term in a multireddit.

I really hope this is doable :)

**Comment by Metalfan666** [comment] 2021-11-26 18:05
Related: #293

**Comment by Wladefant** [comment] 2022-07-31 16:30
Duplicate of #293

**Closed** 2022-07-31 16:30 UTC
