### ISSUE TITLE
[Request] Export and import subreddits

### ISSUE THREAD

**Issue by tegutistgut** [Docile-Alligator/Infinity-For-Reddit#612] opened 2021-12-25 08:12 UTC
Hello.

My request is a feature, where we can export a list of our subscribed/followed subreddits.

And a feature to import a exported list of subscribed/followed subreddits to the "anonymous" account mode.

Thats it

Thanks

**Comment by TheLastZombie** [comment] 2021-12-25 17:02
This is a duplicate of #458, though I haven't been able to find the actual interface - I assume it will arrive with 5.2.

**Comment by Docile-Alligator** [comment] 2022-01-16 01:37
Settings->Advanced->Backup settings will export a list of your subscribed subreddits in anonymous mode.

**Closed by Docile-Alligator** 2022-01-16 01:37 UTC
