### ISSUE TITLE
hide read post automatically not working 

### ISSUE THREAD

**Issue by BigDogg99** [Docile-Alligator/Infinity-For-Reddit#1204] opened 2022-11-05 06:58 UTC
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.4

### Where did you get the app from

Other

### Android version

11

### Device model

poco x2 

### First occurred

4 weeks ago

### Steps to reproduce

1. enable hide read post automatically and  mark post read after scrolling
2. scroll some post, they got mark as readed
3. refresh , marked post got hidden
4. close & open app
5. all post come back ,

### Expected behaviour

post should stay hidden , after reopening the app

### Current behaviour

they come back every time i reopen the app

**Comment by C42EFF4Lbb54dwg** [comment] 2022-12-17 17:43
Facing the same issue on the same version.

**Comment by gbakeman** [comment] 2023-01-03 02:52
Can also confirm seeing this, 1+ 6T running Android 9. I left my setting as they were (all but mark as read on scroll), killed the app and also cleared the cache. Cache clearing was probably unnecessary though.

**Comment by rharish101** [comment] 2023-01-11 12:23
This also happens to me when I upvote/downvote posts without opening the comments. I'm using v5.3.4 from F-Droid.

**Comment by Wladefant** [comment] 2023-02-05 23:48
Only able to reproduce this issue in a multireddit, when not following subreddits. 

Scenario: You are reading multiple posts. You refresh. Only one post gets hidden. The other ones get marked as unread. Every time.

**Closed** 2023-02-06 07:37 UTC
Labels: type: confirmed bug

**Comment by gbakeman** [comment] 2023-02-11 00:46
After updating to the 5.4.0 release on F-Droid, it looks like there was some improvement to the posts staying hidden, but I'm still seeing them come back after reopening the app. It's not consistently reproducible unfortunately, but still happening.
