### ISSUE TITLE
Duplicate Child Comments

### ISSUE THREAD

**Issue by KazKaz90** [Docile-Alligator/Infinity-For-Reddit#883] opened 2022-08-02 03:36 UTC
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.2.1 (100)

### Where did you get the app from

Google Play

### Android version

10

### Device model

TECNO KE7

### First occurred

Idk probably about some weeks ago

### Steps to reproduce

1. Open post
2. Go through comments
3. Open child comments
4. Then the child comments are duplicated

![Screenshot_20220802-112357](https://user-images.githubusercontent.com/90075041/182286467-cf56d0e6-7d16-4354-b239-88e18d920fb2.png)

### Expected behaviour

The child comments should not be duplicate

### Current behaviour

Duplicate child comments

### Logs

No, the app dom't crash for me ever

**Comment by vahaala** [comment] 2022-08-03 13:19
I confirm this happens, it makes it really confusing to know to which parent these comments belong.
![Screenshot_20220803-151627_Infinity](https://user-images.githubusercontent.com/5729654/182617816-0c6cf351-9bbc-4c96-b502-d2120097d13d.jpg)

**Comment by patrickdemers6** [comment] 2022-08-23 18:37
I have not been able to observe this behavior, including on the [post](https://reddit.com/r/Minecraft/comments/vwer6r/i_made_a_simple_texture_pack_to_better_suit_my/) screenshotted by @vahaala. 

Do you have links to posts this is reproducible on?

**Comment by KazKaz90** [comment] 2022-08-24 07:44
> I have not been able to observe this behavior, including on the [post](https://reddit.com/r/Minecraft/comments/vwer6r/i_made_a_simple_texture_pack_to_better_suit_my/) screenshotted by @vahaala. 
> 
> Do you have links to posts this is reproducible on?

There is no specific post because this occurs in every post but does not occur every time.

**Comment by user-727** [comment] 2022-09-02 20:09
I can also confirm this happening in several versions of the app ever since I started using it around a year ago.

**Comment by H-Tevin** [comment] 2022-09-12 18:43
Yep, exact same issue for me. Happens in almost every post with child comments. No rhyme or reason to which ones work fine and which are broken as far as I can tell.

**Comment by Wladefant** [comment] 2022-09-19 07:15
For me it seems tonbe posts with many comments and specifically child comments

**Comment by RSBat** [comment] 2022-11-11 08:51
I think I fugured it out. It is easier to reproduce on slow internet because you need to do some actions while comments are loading.

Prerequisites (it's complicated, but pretty common in large posts) :
"Load more comments" button that will load all children and disappear. I will call this target button. 
Some comments with children that can be collapsed before the target button but not parents of it. Collapsing a comment with about 4 children works best. 
Collapsing those comments should not change position of parent of the target button. 
Some comments after target button. (I think it will crash if there are none) 

For example:
- Top level 1
- - Child 1.1
- - - Child 1.1.1
- - - Child 1.1. 2
- - - .... (more children of 1.1)
- - Target button (Load more comments)
- Top level 2
- - Child 2.1

Steps:
- Click target button
- While comments are loading collapse `Child 1.1`
- Wait for comments to load

Now things are already broken because comments get loaded under `Top level 2` and the button continues to show "Loading"

- Collapse and expand `Top level 1`

"Loading" button button disappears and loaded comments appear under correct parent. But comments under `Top level 2` are still there, so there are duplicate comments.

**Comment by gbakeman** [comment] 2022-11-11 15:36
I thought this was fixed in the last release? At least the problem hasn't been occuring for me anymore.

**Comment by RSBat** [comment] 2022-11-11 19:02
> I thought this was fixed in the last release? At least the problem hasn't been occuring for me anymore.

It was #953. There are some similarities but the two bugs are unrelated

**Closed** 2022-12-03 21:05 UTC
Labels: type: confirmed bug, type: will close on merge
