### ISSUE TITLE
Bug: number of messages in inbox doesn't change unless restarting the app?

### ISSUE THREAD

**Issue by BrodyStone21** [Docile-Alligator/Infinity-For-Reddit#739] opened 2022-04-06 17:41 UTC
Hello, not sure if this is an issue only myself is experiencing, or if others are experiencing it as well. 

Let's say I open Infinity and I have no new messages. The inbox tab will just say "Inbox". Now, let's say that I receive three messages. The inbox tab will now say "Inbox (3)". 

However, after I've read the messages, the inbox tab will still say "Inbox (3)". The only way to fix this is to close the app, and reopen it. Anyone else experiencing this?

**Comment by user-727** [comment] 2022-04-06 19:12
Also experiencing the same behaviour. Pressing the "Read All Messages" from the kebab menu in the inbox, then switching between accounts also gets rid of the unread messages in the Inbox.
Also to note, I only experience this with DMs, inbox messages from post replies (notifications tab) works correctly.

**Comment by hugomg** [comment] 2022-04-11 21:32
This might be a duplicate of #357

**Comment by BrodyStone21** [comment] 2022-04-12 18:11
@hugomg in #357 the OP mentions that the issue persists app/device restart, but mine goes away after restarting the app.

**Comment by Docile-Alligator** [comment] 2022-05-14 11:27
Fixed.

**Closed by Docile-Alligator** 2022-05-14 11:27 UTC
