### ISSUE TITLE
app crashes since last update

### ISSUE THREAD

**Issue by i8cczshd** [Docile-Alligator/Infinity-For-Reddit#545] opened 2021-11-21 15:24 UTC
Infinity v5.1.0
Android 5.1.1

https://user-images.githubusercontent.com/81616288/142768008-5af76d2b-f3b9-4893-a182-f96446a3f613.mp4

**Comment by Docile-Alligator** [comment] 2021-11-22 00:24
Could you go to settings->advanced->crash reports and send the stack trace to me?

**Comment by ind4mnl4t0r** [comment] 2021-11-22 13:08
same issue here.
same app and android version
can't even navigate to the settings->advanced to get the crash report, it keeps crashing. it nearly impossible
but I managed to get the log using root explorer from my device. here's the log


[22-11-2021 183452.txt](https://github.com/Docile-Alligator/Infinity-For-Reddit/files/7581193/22-11-2021.183452.txt)

**Comment by i8cczshd** [comment] 2021-11-23 01:15
> Could you go to settings->advanced->crash reports and send the stack trace to me?

no, the app crashes immediately

**Comment by scria1000** [comment] 2021-11-24 16:17
> same issue here. same app and android version can't even navigate to the settings->advanced to get the crash report, it keeps crashing. it's nearly impossible but I managed to get the log using root explorer from my device. here's the log
> 
> [22-11-2021 183452.txt](https://github.com/Docile-Alligator/Infinity-For-Reddit/files/7581193/22-11-2021.183452.txt)
> 
> edit: app version 5.0.4 works just fine on this device. just tested it.

Hi, sorry about that and thanks for the log. Just tested on a 5.1.1 emulator and the regex pattern `>!(\n?(?:[\S\h]+?(?:\n?[\S\h]+?)?)\n?)!<` mentioned in the logs is indeed the cause of the crash. Apparently , it does not compile below a certain API level. I'll look into it.

**Comment by Docile-Alligator** [comment] 2021-11-25 11:20
@scria1000 Maybe we need to replace \\h with `[ \t\xA0\u1680\u180e\u2000-\u200a\u202f\u205f\u3000]` ?

**Comment by scria1000** [comment] 2021-11-25 16:28
@Docile-Alligator `>!(\n?(?:.+?(?:\n?.+?)?)\n?)!<` ([\S\h]+? replaced with .+?) also does the same thing without crashing but the regex still behaves differently on API level 22, some feature of non-capturing groups is unsupported I think. Besides, the final regex should look like this `>!(\n?(?:.+?(?:\n?.+?)`**`+`**`?)\n?)!<` in order to handle multiline inside the spoiler, but for some reason it causes the app to hang but works fine on desktop. Anyway, PR #537 should fix this.

**Comment by scria1000** [comment] 2021-11-26 12:06
https://github.com/Docile-Alligator/Infinity-For-Reddit/suites/4468046127/artifacts/118823573

Can you install the debug build and tell us whether it still crashes for you?

**Comment by i8cczshd** [comment] 2021-11-30 14:12
works now thx

**Comment by scria1000** [comment] 2021-12-01 18:38
can we close this?

**Comment by i8cczshd** [comment] 2021-12-01 19:38
> can we close this?

yes

**Closed** 2022-01-16 02:53 UTC
