### ISSUE TITLE
Bug: r/ links within comments not shown as links

### ISSUE THREAD

**Issue by austinhuang0131** [Docile-Alligator/Infinity-For-Reddit#27] opened 2019-10-17 04:03 UTC
If a comment only has r/something it shows the link, but if a comment has done other text plus r/something it doesn't show. Proof below, usernames/timestamps censored:

![sketch-1571284765525](https://user-images.githubusercontent.com/16656689/66976890-97c8ca00-f071-11e9-8465-751c0c17e6d3.png)

**Comment by austinhuang0131** [comment] 2019-10-17 04:09
Also this

![_20191017_000843](https://user-images.githubusercontent.com/16656689/66977077-61d81580-f072-11e9-937f-16935f5f5094.JPG)

**Comment by Docile-Alligator** [comment] 2019-10-17 16:31
Yes, I noticed it too. I will try to solve it.

**Comment by Docile-Alligator** [comment] 2019-10-25 15:57
Hi, the problem is now fixed and it will be released in the next update.

**Comment by Wilker-a** [comment] 2019-10-26 21:47
aditionally, the initial slash ('/') before 'r/' or 'u/' are not counted whenever the links are recognized. was that fixed too? :3

**Comment by Docile-Alligator** [comment] 2019-10-27 00:43
@Wilker-a Yes it is fixed too.

**Comment by Wilker-a** [comment] 2019-10-27 04:25
cool, thank you =\^-\^=

**Comment by Docile-Alligator** [comment] 2019-11-01 03:03
You are welcome~

**Closed by Docile-Alligator** 2019-11-01 03:03 UTC
