### ISSUE TITLE
video player in latest update is broken

### ISSUE THREAD

**Issue by BigDogg99** [Docile-Alligator/Infinity-For-Reddit#1123] opened 2022-09-20 17:15 UTC
### Checklist

- [X] I have used the search function for [open](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues) **and** [closed](https://github.com/Docile-Alligator/Infinity-For-Reddit/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only occurs with a certain link, post, image..., I will include the URL.

### App version

5.3.3

### Where did you get the app from

Other

### Android version

11

### Device model

poco x2

### First occurred

while watching videos

### Steps to reproduce

1. play any video
2. single tap on video

### Expected behaviour

it should show controller ui 

### Current behaviour

instead it open full screen video 

### Logs

no logs

**Comment by Wladefant** [comment] 2022-09-20 18:06
Duplicate of #1101

**Closed** 2022-09-20 18:27 UTC
Labels: type: possible bug, close reason: duplicate
